services:
  catalog-service:
    build: ./catalog-service
    ports:
      - "3001:3000"

  catalog-sidecar:
    build: ./catalog-sidecar
    ports:
      - "3002:3000"
    environment:
      - CATALOG_SERVICE_URL=http://catalog-service:3000
    depends_on:
      catalog-service:
        condition: service_healthy

  gateway-service:
    build: ./gateway-service
    ports:
      - "3000:3000"
    environment:
      - CATALOG_SERVICE_URL=http://catalog-sidecar:3000
    depends_on:
      catalog-sidecar:
        condition: service_healthy